server:
  port: 9001
spring:
  datasource:
    username: root
    password: WYZ980417
    url: jdbc:mysql://47.98.246.225:3306/vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.bosssoft.hr.train.authentication.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  instance:
    instance-id: authentication-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
info:
  app:
    name: xx
    description: authentication-server
    version: v1.0