server:
  port: 8001
spring:
  datasource:
    username: root
    password: WYZ980417
    url: jdbc:mysql://47.98.246.225:3306/vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 47.98.246.225
    port: 6379
    password: WYZ980417
    timeout: 300
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  type-aliases-package: com.bosssoft.hr.train.provider.model.po
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  instance:
    instance-id: service-provider
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
info:
  app:
    name: xx
    description: provider
    version: v1.0